name: '[Sync Fork] RSSHub Serverless'

on:
  schedule:
    - cron: '1 0 * * 6' # Runs at 01:00 UTC every Saturday

jobs:
  update_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PAT }}
          upstream_repository: DIYgod/RSSHub
          target_repository: xStar20/RSSHub-Serverless
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
