name: '[Sync Fork] RSSHub Serverless'

on:
  schedule:
    - cron: '0 20 */3 * *' # Runs at 20:00 UTC every 3 days.

jobs:
  update_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PAT }}
          upstream_repository: DIYgod/RSSHub
          target_repository: xStar20/RSSHub-Serverless
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
